/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'signature' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
});
export const LetterId = IDL.Nat;
export const Profile = IDL.Record({
  'signature' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
});
export const StampType = IDL.Variant({
  'indian' : IDL.Null,
  'pakistani' : IDL.Null,
});
export const LetterDetail = IDL.Record({
  'id' : IDL.Nat,
  'from' : IDL.Principal,
  'to' : IDL.Principal,
  'body' : IDL.Text,
  'stamp' : StampType,
  'timestamp' : IDL.Int,
  'signed' : IDL.Bool,
  'deliveryTime' : IDL.Int,
});
export const UserSearchResult = IDL.Record({
  'name' : IDL.Text,
  'city' : IDL.Text,
  'username' : IDL.Text,
  'principal' : IDL.Principal,
});
export const SetUsernameResult = IDL.Variant({
  'ok' : IDL.Null,
  'error' : IDL.Text,
});
export const FriendEntry = IDL.Record({
  'username' : IDL.Text,
  'principal' : IDL.Principal,
});
export const FriendRequestResult = IDL.Variant({
  'ok' : IDL.Null,
  'error' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInbox' : IDL.Func(
      [IDL.Record({ 'userId' : IDL.Principal })],
      [IDL.Vec(LetterId)],
      ['query'],
    ),
  'getOutbox' : IDL.Func(
      [IDL.Record({ 'userId' : IDL.Principal })],
      [IDL.Vec(LetterId)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProfilesByName' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'sendLetter' : IDL.Func(
      [IDL.Principal, IDL.Text, StampType],
      [IDL.Nat],
      [],
    ),
  'getLetter' : IDL.Func([IDL.Nat], [IDL.Opt(LetterDetail)], ['query']),
  'signLetter' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  'getLetterSignature' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'setUsername' : IDL.Func([IDL.Text], [SetUsernameResult], []),
  'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'findUserByUsername' : IDL.Func([IDL.Text], [IDL.Opt(UserSearchResult)], ['query']),
  'sendFriendRequest' : IDL.Func([IDL.Text], [FriendRequestResult], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'removeFriend' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'getFriends' : IDL.Func([], [IDL.Vec(FriendEntry)], ['query']),
  'getPendingFriendRequests' : IDL.Func([], [IDL.Vec(FriendEntry)], ['query']),
});

export const idlFactory = ({ IDL: _IDL }) => idlService;

export const init = ({ IDL }) => { return []; };
