/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'signature' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
});
export const LetterId = IDL.Nat;
export const Profile = IDL.Record({
  'signature' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
});
export const StampType = IDL.Variant({
  'indian' : IDL.Null,
  'pakistani' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInbox' : IDL.Func(
      [IDL.Record({ 'userId' : IDL.Principal })],
      [IDL.Vec(LetterId)],
      ['query'],
    ),
  'getOutbox' : IDL.Func(
      [IDL.Record({ 'userId' : IDL.Principal })],
      [IDL.Vec(LetterId)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProfilesByName' : IDL.Func([IDL.Text], [IDL.Vec(Profile)], ['query']),
  'sendLetter' : IDL.Func([IDL.Principal, IDL.Text, StampType], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'signature' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
  });
  const LetterId = IDL.Nat;
  const Profile = IDL.Record({
    'signature' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
  });
  const StampType = IDL.Variant({
    'indian' : IDL.Null,
    'pakistani' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInbox' : IDL.Func(
        [IDL.Record({ 'userId' : IDL.Principal })],
        [IDL.Vec(LetterId)],
        ['query'],
      ),
    'getOutbox' : IDL.Func(
        [IDL.Record({ 'userId' : IDL.Principal })],
        [IDL.Vec(LetterId)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProfilesByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Profile)],
        ['query'],
      ),
    'sendLetter' : IDL.Func(
        [IDL.Principal, IDL.Text, StampType],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };