/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type LetterId = bigint;
export interface Profile {
  'signature' : string,
  'city' : string,
  'name' : string,
}
export type StampType = { 'indian' : null } |
  { 'pakistani' : null };
export interface UserProfile {
  'signature' : string,
  'city' : string,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface LetterDetail {
  'id' : bigint,
  'from' : Principal,
  'to' : Principal,
  'body' : string,
  'stamp' : StampType,
  'timestamp' : bigint,
  'signed' : boolean,
  'deliveryTime' : bigint,
}
export interface UserSearchResult {
  'name' : string,
  'city' : string,
  'username' : string,
  'principal' : Principal,
}
export type SetUsernameResult = { 'ok' : null } |
  { 'error' : string };
export interface FriendEntry {
  'username' : string,
  'principal' : Principal,
}
export type FriendRequestResult = { 'ok' : null } |
  { 'error' : string };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUsernameAvailable' : ActorMethod<[string], boolean>,
  'findUserByUsername' : ActorMethod<[string], [] | [UserSearchResult]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInbox' : ActorMethod<[{ 'userId' : Principal }], Array<LetterId>>,
  'getLetter' : ActorMethod<[bigint], [] | [LetterDetail]>,
  'getLetterSignature' : ActorMethod<[bigint], [] | [string]>,
  'getMyUsername' : ActorMethod<[], [] | [string]>,
  'getOutbox' : ActorMethod<[{ 'userId' : Principal }], Array<LetterId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProfilesByName' : ActorMethod<[string], Array<Profile>>,
  'sendLetter' : ActorMethod<[Principal, string, StampType], bigint>,
  'setUsername' : ActorMethod<[string], SetUsernameResult>,
  'signLetter' : ActorMethod<[bigint, string], boolean>,
  'sendFriendRequest' : ActorMethod<[string], FriendRequestResult>,
  'acceptFriendRequest' : ActorMethod<[Principal], boolean>,
  'declineFriendRequest' : ActorMethod<[Principal], boolean>,
  'removeFriend' : ActorMethod<[Principal], boolean>,
  'getFriends' : ActorMethod<[], Array<FriendEntry>>,
  'getPendingFriendRequests' : ActorMethod<[], Array<FriendEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
